# Generated by Django 5.0.6 on 2024-06-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_delete_remove_destination_imagenciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='imagenCiudad',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
